services:
  nextjs-app:
    image: ghcr.io/chidung091/nextjs-app:latest # Placeholder for pushing image to Dockerhub
    build:
      context: .
      dockerfile: Dockerfile
  nginx:
    image: ghcr.io/chidung091/nextjs-app:latest # Placeholder for pushing image to Dockerhub
    build:
      context: ./nginx-docker
      dockerfile: Dockerfile
    depends_on:
      - nextjs-app
    ports:
      - "80:8080"
    environment:
      - NEXTJS_CONTAINER_IP=nextjs-app # supplying environment vars for convert-nginx.sh file.
    command: ["sh", "/etc/nginx/convert-nginx.sh"]
    # this is for parsing the convert-nginx.sh file into nginx.conf file after supplying environment vars,
    # to get the resultant nginx.conf file in different environments.
    # We also supply kubernetes specific env vars in deployment.yml file
