name: Deploy to DigitalOcean (Dev and Prod)

on:
  repository_dispatch:
    types: [deploy_dev, deploy_prod]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev, prod]

    steps:
      - name: Check if the secret exists
          run: |
            if [ -z "${{ secrets.DO_DEV_PASSWORD }}" ]; then
              echo "DO_DEV_PASSWORD is not set."
              exit 1
            else
              echo "DO_DEV_PASSWORD is set."
            fi
      - name: Only run for dev environment
        if: github.event.action == 'deploy_dev' && matrix.environment == 'dev'
        run: echo "Deploying to development environment"

      - name: Only run for prod environment
        if: github.event.action == 'deploy_prod' && matrix.environment == 'prod'
        run: echo "Deploying to production environment"

      - name: Connect to DigitalOcean via SSH and deploy (Dev)
        if: github.event.action == 'deploy_dev' && matrix.environment == 'dev'
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DO_DEV_DROPLET_IP }}
          username: ${{ secrets.DO_DEV_DROPLET_USER }}
          password: ${{ secrets.DO_DEV_PASSWORD }}
          port: 22
          script: |
            cd cm-deployment
            docker-compose -f docker-compose.dev.yml pull
            docker-compose -f docker-compose.dev.yml up -d

      - name: Connect to DigitalOcean via SSH and deploy (Prod)
        if: github.event.action == 'deploy_prod' && matrix.environment == 'prod'
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DO_PROD_DROPLET_IP }}
          username: ${{ secrets.DO_PROD_DROPLET_USER }}
          password: ${{ secrets.DO_PROD_PASSWORD }}
          port: 22
          script: |
            cd cm-deployment
            docker-compose -f docker-compose.prod.yml pull
            docker-compose -f docker-compose.prod.yml up -d
