name: Deploy to DigitalOcean (Dev and Prod)

on:
  repository_dispatch:
    types: [deploy_dev, deploy_prod]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev, prod]

    steps:
      - name: Only run for matching environment
        if: github.event.action == 'deploy_' + matrix.environment
        run: echo "Deploying to ${{ matrix.environment }} environment"

      - name: Connect to DigitalOcean via SSH and deploy
        if: github.event.action == 'deploy_' + matrix.environment
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets["DO_" + matrix.environment | upper + "_DROPLET_IP"] }}
          username: ${{ secrets["DO_" + matrix.environment | upper + "_DROPLET_USER"] }}
          password: ${{ secrets["DO_" + matrix.environment | upper + "_PASSWORD"] }}
          port: 22
          script: |
            cd /path/to/${{ matrix.environment }}/deployment-folder
            docker-compose -f docker-compose.${{ matrix.environment }}.yml pull
            docker-compose -f docker-compose.${{ matrix.environment }}.yml up -d
