name: Deploy to DigitalOcean (Dev and Prod)

on:
  repository_dispatch:
    types: [deploy_dev, deploy_prod]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev, prod]

    steps:
      - name: Only run for matching environment
        if: github.event.action == 'deploy_' + matrix.environment
        run: echo "Deploying to ${{ matrix.environment }} environment"

      - name: Connect to DigitalOcean via SSH and deploy (Dev)
        if: matrix.environment == 'dev' && github.event.action == 'deploy_dev'
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DO_DEV_DROPLET_IP }}
          username: ${{ secrets.DO_DEV_DROPLET_USER }}
          password: ${{ secrets.DO_DEV_PASSWORD }}
          port: 22
          script: |
            cd cm-deployment
            docker-compose -f docker-compose.dev.yml pull
            docker-compose -f docker-compose.dev.yml up -d

      - name: Connect to DigitalOcean via SSH and deploy (Prod)
        if: matrix.environment == 'prod' && github.event.action == 'deploy_prod'
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DO_PROD_DROPLET_IP }}
          username: ${{ secrets.DO_PROD_DROPLET_USER }}
          password: ${{ secrets.DO_PROD_PASSWORD }}
          port: 22
          script: |
            cd cm-deployment
            docker-compose -f docker-compose.prod.yml pull
            docker-compose -f docker-compose.prod.yml up -d
