name: Deploy to DigitalOcean

on:
  repository_dispatch:
    types: [deploy] # This is triggered by the cm repository

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Connect to DigitalOcean via SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd cm-deployment
            docker-compose pull
            docker-compose up -d
